#!/usr/bin/env python3
import argparse
import logging

from find_kallsyms import find_kallsyms_in_rodata


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--verbose', action='store_true')
    parser.add_argument('path')
    args = parser.parse_args()
    if args.verbose:
        logging.basicConfig(level=logging.DEBUG)
    with open(args.path, 'rb') as fp:
        rodata = fp.read()
    for address, name in find_kallsyms_in_rodata(rodata):
        print('{:016X} {}'.format(address, name))


if __name__ == '__main__':
    main()
