on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

name: Continuous integration

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3

    - name: Install packages
      run: sudo apt-get update &&
           sudo apt-get install -y black flake8 python2 python3 jython pypy3

    - name: Check formatting
      run: ./black --check

    - name: Test python2
      run: python2 -m unittest discover

    - name: Test python3
      run: python2 -m unittest discover

    - name: Test jython
      run: jython -m unittest discover

    - name: Test pypy3
      run: pypy3 -m unittest discover
